INSERT INTO questions (text, reference_answer, unit, unit_plural, category, difficulty, explanation, estimation_approach, hint, source, source_name, reference_period, uncertainty_low, uncertainty_high, tags, status) VALUES 
(
  'How many parameters does the GPT-4 model have (according to industry estimates)?',
  1760000000000,
  'parameter',
  'parameters',
  'technology',
  'medium',
  'While OpenAI hasn''t officially confirmed it, widely accepted leaks and industry consensus estimate GPT-4 uses a Mixture of Experts (MoE) architecture with roughly 1.76 trillion parameters across 8 expert models.',
  'GPT-3 had 175 billion. Models scaled up roughly 10x for the next generation. 175B × 10 = ~1.75 Trillion.',
  'GPT-3 had 175 billion parameters. GPT-4 is estimated to be roughly 10 times larger.',
  NULL,
  'Industry Estimates / SemiAnalysis',
  '2023',
  1500000000000,
  2000000000000,
  ARRAY['AI', 'LLM', 'OpenAI', 'technology']::text[],
  'active'
),
(
  'How much did it cost to train GPT-4 in computing power alone (USD)?',
  63000000,
  'USD',
  'USD',
  'technology',
  'hard',
  'It is estimated that training GPT-4 cost roughly $63 million in compute time alone, requiring thousands of A100 GPUs running continuously for months.',
  'Assume 10,000 A100 GPUs at ~$2/hour for 90 days. 10,000 × 2 × 24 × 90 = $43.2M. Add overhead and failed runs to reach ~$60M+.',
  'Think about thousands of highly expensive GPUs running 24/7 for a few months.',
  NULL,
  'AI Research Estimates',
  '2023',
  40000000,
  100000000,
  ARRAY['AI', 'training', 'compute', 'cost']::text[],
  'active'
),
(
  'How many active users did ChatGPT reach just two months after its launch?',
  100000000,
  'user',
  'users',
  'technology',
  'easy',
  'ChatGPT reached 100 million monthly active users in January 2023, just two months after launch, making it the fastest-growing consumer application in history at the time.',
  'It famously broke TikTok''s record (9 months) and Instagram''s record (2.5 years) to reach the 100 million milestone in a fraction of the time.',
  'It broke the record for the fastest-growing app in history, hitting a massive 9-figure milestone.',
  NULL,
  'UBS / Similarweb',
  '2023',
  90000000,
  110000000,
  ARRAY['ChatGPT', 'growth', 'users', 'AI']::text[],
  'active'
),
(
  'How many Nvidia H100 GPUs did Meta announce they would stockpile by the end of 2024?',
  350000,
  'GPU',
  'GPUs',
  'technology',
  'medium',
  'Mark Zuckerberg announced that Meta is building massive compute infrastructure that will include 350,000 Nvidia H100 GPUs by the end of 2024.',
  'Large tech companies usually buy GPUs in clusters of 10,000 to 30,000. Meta is going all-in on AGI, so multiply that by 10 or 20.',
  'A massive number, enough to cost billions of dollars just in silicon.',
  NULL,
  'Meta Announcements',
  '2024',
  300000,
  400000,
  ARRAY['Meta', 'GPU', 'hardware', 'AI']::text[],
  'active'
),
(
  'How many tokens (words/subwords) was Llama 3 (8B & 70B) trained on?',
  15000000000000,
  'token',
  'tokens',
  'technology',
  'hard',
  'Meta trained its Llama 3 models on a massive dataset of 15 trillion tokens, which is significantly larger than the training sets used for Llama 2 (2 trillion).',
  'Previous generation models used 1-2 trillion tokens. The ''Chinchilla scaling laws'' showed that models benefit from much more data, so Meta massively increased the training set size by ~7x.',
  'Previous models used about 2 trillion tokens. Llama 3 used a significantly larger dataset, well into the double-digit trillions.',
  NULL,
  'Meta AI',
  '2024',
  14000000000000,
  16000000000000,
  ARRAY['LLM', 'tokens', 'Meta', 'Llama']::text[],
  'active'
),
(
  'How many liters of water does it take to produce one almond?',
  12,
  'liter',
  'liters',
  'nature',
  'medium',
  'It takes approximately 12 liters (or about 3.2 gallons) of water to grow a single almond, making them one of the most water-intensive crops in California.',
  'Nuts are highly water-intensive. Think about how much water a tree needs over months to produce a small yield of nuts.',
  'It takes more than 10 liters but less than 20.',
  NULL,
  'Water Footprint Network',
  '2023',
  10,
  15,
  ARRAY['water', 'food', 'environment']::text[],
  'active'
),
(
  'How many commercial flights take off every day worldwide?',
  100000,
  'flight',
  'flights',
  'infrastructure',
  'easy',
  'There are roughly 100,000 commercial flights per day globally. This fluctuates slightly by season but remains relatively steady.',
  'Major airports handle ~1,000 flights a day. There are dozens of major hubs and thousands of smaller ones. 100,000 is the widely accepted industry average.',
  'Think about how many major airports exist and multiply by daily traffic.',
  NULL,
  'FlightRadar24',
  '2023',
  80000,
  120000,
  ARRAY['aviation', 'travel', 'transportation']::text[],
  'active'
),
(
  'How many bones are in the adult human body?',
  206,
  'bone',
  'bones',
  'science',
  'easy',
  'A typical adult human has 206 bones. Infants are born with around 300, but many fuse together as they grow.',
  'Hands and feet have many small bones (about 100 total). Ribs add 24. Spine has 26. Skull and limbs make up the rest.',
  'Infants have about 300, but adults have around 100 fewer because they fuse together.',
  NULL,
  'Anatomy reference',
  'Constant',
  206,
  206,
  ARRAY['biology', 'human body', 'anatomy']::text[],
  'active'
),
(
  'How many miles of blood vessels are in the human body?',
  60000,
  'mile',
  'miles',
  'science',
  'unhinged',
  'The human body contains approximately 60,000 miles (nearly 100,000 km) of blood vessels, enough to wrap around the Earth more than twice.',
  'Capillaries are microscopic but incredibly dense to reach every cell. The sheer number of them adds up to immense length.',
  'It''s enough to wrap around the Earth (25,000 miles) more than twice.',
  NULL,
  'Cleveland Clinic',
  'Constant',
  50000,
  70000,
  ARRAY['biology', 'anatomy', 'blood']::text[],
  'active'
),
(
  'What is the top speed of a cheetah in km/h?',
  120,
  'km/h',
  'km/h',
  'animals',
  'easy',
  'Cheetahs can sprint at speeds up to 120 km/h (75 mph) in short bursts covering distances up to 500 meters.',
  'Highway speed limit is typically 100-120 km/h. Cheetahs can match a car on a highway.',
  'They can run about as fast as a car driving on a highway.',
  NULL,
  'National Geographic',
  'Constant',
  110,
  130,
  ARRAY['animals', 'speed', 'nature']::text[],
  'active'
);
