-- Insert Seed Questions
INSERT INTO questions (
  text,
  reference_answer,
  unit,
  unit_plural,
  category,
  difficulty,
  explanation,
  estimation_approach,
  hint,
  source,
  source_name,
  reference_period,
  uncertainty_low,
  uncertainty_high,
  tags,
  status
) VALUES 
(
      'How many emails are sent worldwide every day?',
      333000000000,
      'email',
      'emails',
      'technology',
      'medium',
      'Email traffic totals roughly 333 billion emails per day as of 2022–2023, including spam. Legitimate business emails account for around 100–120 billion. Spam constitutes the majority.',
      'World population ~8 billion. Perhaps 4 billion email users. If each sends/receives ~80 emails per day on average (including spam), that''s 4B × 80 = 320 billion. Add automated and business traffic.',
      'Think about how many people have email and how often they use it — then consider automated and spam emails.',
      'https://www.statista.com/statistics/456500/daily-number-of-e-mails-worldwide/',
      'Statista',
      '2023',
      300000000000,
      370000000000,
      ARRAY['email', 'internet', 'communication']::text[],
      'active'
    ),
(
      'How many active websites exist on the internet?',
      200000000,
      'website',
      'websites',
      'technology',
      'medium',
      'Of the roughly 1.1 billion registered domain names, approximately 200 million host active websites with real content. The rest are parked, unused, or redirect domains.',
      'Start with ~1 billion registered domains. Estimate that 15–20% are actively maintained. That gives 150–200 million active sites.',
      'There are over a billion registered domains, but most are parked or unused.',
      'https://www.internetlivestats.com/total-number-of-websites/',
      'Internet Live Stats',
      '2023',
      170000000,
      250000000,
      ARRAY['internet', 'web', 'domains']::text[],
      'active'
    ),
(
      'How many hours of video are uploaded to YouTube every minute?',
      500,
      'hour',
      'hours',
      'technology',
      'easy',
      'YouTube users upload approximately 500 hours of video per minute. At this rate, it would take a single person over 82 years to watch all the content uploaded in one day.',
      'YouTube has ~2 billion logged-in users per month. If even 0.001% upload a 5-minute video per day, that''s 2M × 0.001% = 20,000 videos × 5 min = 100,000 min / 1440 min per day ≈ 69 hours per minute. Add professional and automated uploads.',
      'Consider how many creators are active and how many minutes of video they produce.',
      'https://blog.youtube/',
      'YouTube Official Blog',
      '2022',
      450,
      550,
      ARRAY['youtube', 'video', 'uploads']::text[],
      'active'
    ),
(
      'How many transistors are in a modern high-end smartphone processor?',
      16000000000,
      'transistor',
      'transistors',
      'technology',
      'hard',
      'Modern smartphone chips like the Apple A17 Pro contain approximately 19 billion transistors on a 3nm process. The average across flagship chips is roughly 10–16 billion.',
      'Moore''s Law doubles transistors every ~2 years. In 2010, flagship chips had ~1 billion. By 2023 (roughly 13 years, ~6.5 doublings), that''s 1B × 2^6.5 ≈ 91B. Modern chips are at 10–20B on 3–5nm nodes.',
      'Think about how chip density has grown — transistors are now measured in nanometers.',
      'https://www.apple.com/iphone-15-pro/',
      'Apple',
      '2023',
      10000000000,
      20000000000,
      ARRAY['semiconductors', 'chips', 'Apple', 'processor']::text[],
      'active'
    ),
(
      'How many Google searches are performed every day?',
      8500000000,
      'search',
      'searches',
      'technology',
      'medium',
      'Google processes approximately 8.5 billion searches per day as of 2023, which equates to roughly 100,000 searches per second.',
      '~5 billion internet users. If each performs 1–2 searches per day on average, that''s 5–10 billion. Google holds ~92% market share, so this aligns with ~8.5 billion.',
      'Think about internet users and how often you personally search on a typical day.',
      'https://www.internetlivestats.com/google-search-statistics/',
      'Internet Live Stats',
      '2023',
      7000000000,
      10000000000,
      ARRAY['google', 'search', 'internet']::text[],
      'active'
    ),
(
      'How many apps are available in the Apple App Store?',
      1800000,
      'app',
      'apps',
      'technology',
      'medium',
      'The Apple App Store contains approximately 1.8 million apps as of 2023. This is down from a peak of around 2.2 million as Apple removed low-quality apps.',
      'App Store launched in 2008 with ~500 apps. Growth was rapid in early years, slower later. By 2023, roughly 1.5–2 million apps remain after pruning.',
      'The App Store has existed for over 15 years and millions of developers have submitted apps.',
      'https://www.statista.com/statistics/779768/number-of-available-apps-in-the-apple-app-store-quarter/',
      'Statista',
      '2023',
      1500000,
      2100000,
      ARRAY['Apple', 'App Store', 'apps', 'mobile']::text[],
      'active'
    ),
(
      'How much data does a typical Netflix stream use per hour in HD?',
      3000,
      'MB',
      'MB',
      'technology',
      'easy',
      'Netflix uses approximately 3 GB (3,000 MB) per hour for HD streaming and 7 GB per hour for 4K Ultra HD. SD uses around 1 GB per hour.',
      'HD video at 1080p requires roughly 5–8 Mbps. Over an hour (3600 seconds): 6 Mbps × 3600s = 21,600 Mb = 2,700 MB ≈ 3 GB.',
      'Think about video bitrate in megabits per second and multiply by seconds in an hour.',
      NULL,
      'Netflix Help',
      '2023',
      2500,
      4000,
      ARRAY['Netflix', 'streaming', 'data', 'bandwidth']::text[],
      'active'
    ),
(
      'How many lines of code does the Windows operating system contain (approximately)?',
      50000000,
      'line of code',
      'lines of code',
      'technology',
      'hard',
      'Windows XP had approximately 45 million lines of code. Modern Windows versions are estimated at 50–80 million lines. This is a rough industry estimate, not a published Microsoft figure.',
      'Large enterprise software has millions of lines. Linux kernel has ~30 million. Windows is more complex. Industry estimates suggest 50–80 million across the full OS.',
      'The Linux kernel alone has tens of millions of lines. Windows is considerably larger.',
      NULL,
      'Industry estimates',
      '2023',
      40000000,
      80000000,
      ARRAY['Windows', 'software', 'code', 'Microsoft']::text[],
      'active'
    ),
(
      'How many active GitHub repositories exist?',
      420000000,
      'repository',
      'repositories',
      'technology',
      'medium',
      'GitHub reported over 420 million total repositories in 2023. The number of actively maintained repositories is significantly lower, but the total count includes all public and private repos.',
      'GitHub has ~100 million developers. If each creates an average of 4–5 repositories over their lifetime, that''s 400–500 million total repositories.',
      'Think about how many developers use GitHub and how many projects each person might create.',
      'https://github.blog/',
      'GitHub Blog',
      '2023',
      350000000,
      500000000,
      ARRAY['GitHub', 'code', 'developers', 'open source']::text[],
      'active'
    ),
(
      'How many messages are sent on WhatsApp every day?',
      100000000000,
      'message',
      'messages',
      'technology',
      'medium',
      'WhatsApp processes approximately 100 billion messages per day as of 2020. This includes text, voice, and image messages sent to individuals and groups.',
      'WhatsApp has ~2 billion users. If each active user sends an average of 50 messages per day, that''s 2B × 50 = 100 billion messages.',
      'WhatsApp has 2 billion users. Consider how many messages a typical user sends daily.',
      NULL,
      'Meta (WhatsApp)',
      '2020',
      80000000000,
      120000000000,
      ARRAY['WhatsApp', 'messaging', 'Meta']::text[],
      'active'
    ),
(
      'How many terabytes of data does Google process per day?',
      100000000,
      'TB',
      'TB',
      'technology',
      'hard',
      'Google processes roughly 100 petabytes (100 million TB) per day across all its services including search indexing, YouTube, Gmail, Maps, and advertising systems. This is a rough industry estimate.',
      '8.5B searches/day × a few KB each = small. YouTube: 500 hours uploaded/min × 60 min/hr × 24 hrs × 1 GB/hr = ~720 TB/day just in uploads. Total across all Google services adds up to exabyte-scale.',
      'Think about YouTube alone — 500 hours of video uploaded per minute — then add everything else.',
      NULL,
      'Industry estimates',
      '2023',
      20000000,
      500000000,
      ARRAY['Google', 'data', 'cloud', 'big data']::text[],
      'active'
    ),
(
      'How many iPhones has Apple sold in total since the first iPhone in 2007?',
      2300000000,
      'iPhone',
      'iPhones',
      'technology',
      'medium',
      'Apple has sold approximately 2.3 billion iPhones cumulatively since the original launch in 2007, based on annual unit sales data through 2023.',
      'Apple sells ~220–230 million iPhones per year currently. In earlier years, sales were lower. Rough total from 2007–2023: sum of growing annual sales ≈ 2–2.5 billion.',
      'Apple currently sells about 220 million iPhones per year. How many years has it been selling them, and how did sales grow over time?',
      NULL,
      'Apple financial reports',
      '2007–2023',
      2000000000,
      2600000000,
      ARRAY['Apple', 'iPhone', 'smartphone', 'sales']::text[],
      'active'
    ),
(
      'How many people in the world have access to the internet?',
      5400000000,
      'person',
      'people',
      'technology',
      'easy',
      'Approximately 5.4 billion people (67% of the global population of ~8 billion) had internet access as of 2023. Penetration varies significantly by region.',
      'World population ~8 billion. Internet penetration is roughly 65–70% globally. 8B × 0.67 ≈ 5.4 billion.',
      'Think about what fraction of the world''s 8 billion people might have internet access — consider that many developing regions are still getting connected.',
      NULL,
      'ITU / Statista',
      '2023',
      5000000000,
      5700000000,
      ARRAY['internet', 'access', 'global', 'connectivity']::text[],
      'active'
    ),
(
      'How many Raspberry Pi computers have been sold since 2012?',
      60000000,
      'unit',
      'units',
      'technology',
      'hard',
      'The Raspberry Pi Foundation announced selling its 50 millionth Raspberry Pi in 2022. Cumulative sales through 2023 are estimated at approximately 55–65 million units.',
      'Early years: 1–2M/year. Peak years post-COVID demand: 5–7M/year. Over 10 years averaging 5M/year = 50M+ cumulative.',
      'Raspberry Pi launched in 2012 and became wildly popular in education and hobby electronics.',
      NULL,
      'Raspberry Pi Foundation',
      '2012–2023',
      55000000,
      65000000,
      ARRAY['Raspberry Pi', 'hardware', 'maker', 'education']::text[],
      'active'
    ),
(
      'How much electricity does a gaming desktop PC use per year if played for 4 hours daily?',
      365,
      'kWh',
      'kWh',
      'technology',
      'medium',
      'A gaming PC draws approximately 300–400W under load. At 4 hours/day: 350W × 4h × 365 days = 511 kWh/year. In idle or low-load states, consumption is lower. A reasonable estimate is 250–400 kWh/year.',
      'Gaming PC ≈ 300W. 4 hours/day × 365 days = 1,460 hours. 300W × 1,460h = 438,000 Wh = 438 kWh/year.',
      'Start with how many watts a gaming PC draws, then multiply by hours used per year.',
      NULL,
      'Energy consumption estimates',
      '2023',
      250,
      550,
      ARRAY['electricity', 'gaming', 'energy', 'PC']::text[],
      'active'
    ),
(
      'How many cells are in the human body?',
      37000000000000,
      'cell',
      'cells',
      'science',
      'hard',
      'The human body contains approximately 37 trillion cells. This estimate comes from a 2013 study published in Annals of Human Biology. Red blood cells are most numerous at ~25 trillion.',
      'Average cell diameter ~10 micrometers. Human body volume ~65 liters. But cells vary enormously in size. Scientific count: ~37 trillion total cells.',
      'Red blood cells alone number in the trillions — and the body has many types of cells.',
      'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3905396/',
      'Bianconi et al., 2013',
      '2013',
      30000000000000,
      40000000000000,
      ARRAY['biology', 'cells', 'human body']::text[],
      'active'
    ),
(
      'How many neurons are in the human brain?',
      86000000000,
      'neuron',
      'neurons',
      'science',
      'medium',
      'The human brain contains approximately 86 billion neurons, a figure established by Azevedo et al. in 2009 using isotropic fractionation. The often-cited ''100 billion'' figure is a rough earlier estimate.',
      'The cerebral cortex contains ~16B neurons. Cerebellum contains ~69B. Other regions add the remainder. Total ≈ 86B.',
      'The brain has different regions with different neuron densities — the cerebellum alone contains most of them.',
      'https://www.jneurosci.org/content/29/35/10891',
      'Azevedo et al., 2009',
      '2009',
      80000000000,
      90000000000,
      ARRAY['neuroscience', 'brain', 'biology']::text[],
      'active'
    ),
(
      'How fast does light travel in kilometers per second?',
      299792,
      'km/s',
      'km/s',
      'science',
      'medium',
      'The speed of light in a vacuum is exactly 299,792.458 km/s (approximately 300,000 km/s). This is a fundamental physical constant.',
      'A classic physics constant. Light travels roughly 300,000 km per second, or about 7.5 times around the Earth in one second.',
      'Light can circle the Earth about 7 times per second.',
      NULL,
      'NIST',
      'Constant',
      299792,
      299793,
      ARRAY['physics', 'light', 'constants', 'speed']::text[],
      'active'
    ),
(
      'How many known species of insects exist on Earth?',
      1000000,
      'species',
      'species',
      'science',
      'medium',
      'Approximately 1 million insect species have been formally described and catalogued. Total insect species on Earth may be 5–10 million, with many yet undiscovered.',
      'Insects are the most species-diverse class of animals. Described species across all life: ~8.7M. Insects represent ~70% of known animal species ≈ ~1M.',
      'Insects make up the vast majority of all known animal species.',
      NULL,
      'IUCN / Catalogue of Life',
      '2023',
      900000,
      1100000,
      ARRAY['insects', 'biodiversity', 'taxonomy']::text[],
      'active'
    ),
(
      'How many atoms are in a grain of sand?',
      43000000000000000000,
      'atom',
      'atoms',
      'science',
      'unhinged',
      'A grain of sand (SiO₂) weighs roughly 0.06 mg. Molar mass of SiO₂ is 60.1 g/mol. Moles in 0.06mg = 0.06×10⁻³/60.1 ≈ 1×10⁻⁶ mol. × Avogadro''s number (6×10²³) = ~6×10¹⁷ × 3 atoms per molecule ≈ 2×10¹⁸ atoms.',
      'Mass of grain ÷ molar mass × Avogadro''s number × atoms per molecule.',
      'Think about Avogadro''s number (6×10²³) and the mass of a grain of sand.',
      NULL,
      'Physical chemistry calculation',
      'Constant',
      10000000000000000000,
      100000000000000000000,
      ARRAY['physics', 'chemistry', 'atoms', 'scale']::text[],
      'active'
    ),
(
      'What is the approximate diameter of a human hair in micrometers?',
      70,
      'micrometer',
      'micrometers',
      'science',
      'easy',
      'Human hair varies from about 50 to 100 micrometers in diameter, with a typical value around 70 micrometers (0.07mm).',
      'A micrometer is one millionth of a meter. Human hair is about 0.05–0.1mm thick. 0.07mm = 70 micrometers.',
      'A human hair is about 0.07mm thick. Convert to micrometers.',
      NULL,
      'Biology reference',
      'Constant',
      50,
      100,
      ARRAY['biology', 'measurement', 'human body']::text[],
      'active'
    ),
(
      'How many times does the human heart beat in a lifetime (average 79 years)?',
      2900000000,
      'heartbeat',
      'heartbeats',
      'science',
      'easy',
      'At a resting heart rate of ~70 bpm, over 79 years: 70 × 60 × 24 × 365 × 79 ≈ 2.9 billion heartbeats.',
      '70 beats/min × 60 min/hr × 24 hr/day × 365 days/yr × 79 years = 2,908,296,000 ≈ 2.9 billion.',
      'Start with beats per minute, then multiply up through minutes, hours, days, and years.',
      NULL,
      'Calculation based on average heart rate',
      'Reference',
      2500000000,
      3500000000,
      ARRAY['biology', 'heart', 'human body', 'lifetime']::text[],
      'active'
    ),
(
      'How many bacteria live in the human gut?',
      38000000000000,
      'bacterium',
      'bacteria',
      'science',
      'hard',
      'The human gut contains approximately 38 trillion bacteria, roughly equal to the number of human cells in the body. This was revised down from earlier estimates of 100 trillion.',
      'The large intestine contains densely packed microbial communities. A 2016 study by Sender et al. revised estimates to ~38 trillion gut bacteria.',
      'The gut microbiome is often described as containing ''as many bacteria as human cells.''',
      'https://www.cell.com/cell/fulltext/S0092-8674(16)30750-6',
      'Sender et al., 2016',
      '2016',
      30000000000000,
      50000000000000,
      ARRAY['biology', 'microbiome', 'gut', 'bacteria']::text[],
      'active'
    ),
(
      'What is the total land area of Africa in square kilometers?',
      30370000,
      'km²',
      'km²',
      'geography',
      'medium',
      'Africa covers approximately 30.37 million km², making it the world''s second-largest continent. It is often depicted as smaller than it actually is due to Mercator projection distortions.',
      'Africa spans roughly 8,000 km north-to-south and 7,400 km east-to-west. Rectangle approximation: 8,000 × 7,400 = 59.2M km². Adjust for actual irregular shape: roughly half ≈ 30M km².',
      'Africa is roughly 8,000 km tall and 7,000 km wide at its widest — but not a rectangle.',
      NULL,
      'World Atlas',
      'Reference',
      30000000,
      31000000,
      ARRAY['Africa', 'land area', 'continent', 'geography']::text[],
      'active'
    ),
(
      'How long is the Amazon River in kilometers?',
      6992,
      'km',
      'km',
      'geography',
      'medium',
      'The Amazon River is approximately 6,992 km long (some sources say up to 7,062 km depending on measurement methodology), making it one of the world''s two longest rivers alongside the Nile.',
      'South America is ~7,500 km long. The Amazon runs roughly west to east across the continent. Accounting for its winding path, 7,000 km is a reasonable estimate.',
      'The Amazon crosses most of South America. South America itself is about 7,000 km long.',
      NULL,
      'USGS / National Geographic',
      'Reference',
      6800,
      7100,
      ARRAY['Amazon', 'river', 'South America', 'geography']::text[],
      'active'
    ),
(
      'What is the population of Brazil?',
      215000000,
      'person',
      'people',
      'geography',
      'easy',
      'Brazil had a population of approximately 215 million people as of 2023, making it the largest country in South America and the sixth most populous country in the world.',
      'South America''s total population is ~430M. Brazil is the dominant country. Brazil alone has about half the continent''s population.',
      'Brazil is the largest and most populous country in South America, which has about 430 million people total.',
      NULL,
      'UN Population Division',
      '2023',
      210000000,
      220000000,
      ARRAY['Brazil', 'population', 'South America']::text[],
      'active'
    ),
(
      'How deep is the Mariana Trench at its deepest point in meters?',
      10935,
      'meter',
      'meters',
      'geography',
      'medium',
      'The Challenger Deep in the Mariana Trench reaches approximately 10,935 meters (35,876 feet) below sea level. It is the deepest known point on Earth''s surface.',
      'The ocean average depth is ~3,700m. The Mariana Trench is known to be far deeper than average. Atmospheric pressure context: every 10m of water ≈ 1 atm. At 10,935m ≈ 1,094 atm.',
      'The deepest point on Earth is in the Pacific Ocean — roughly 11 km below the surface.',
      NULL,
      'NOAA',
      'Reference',
      10800,
      11000,
      ARRAY['ocean', 'Mariana Trench', 'depth', 'geography']::text[],
      'active'
    ),
(
      'How many countries are in Africa?',
      54,
      'country',
      'countries',
      'geography',
      'easy',
      'Africa contains 54 recognized sovereign states. This is the most of any continent.',
      'Africa is large and historically was divided by European colonizers into many territories. After independence movements, these became sovereign states.',
      'Africa has more countries than any other continent.',
      NULL,
      'United Nations',
      '2023',
      54,
      54,
      ARRAY['Africa', 'countries', 'geography']::text[],
      'active'
    ),
(
      'How many kilometers of coastline does Canada have?',
      202080,
      'km',
      'km',
      'geography',
      'hard',
      'Canada has approximately 202,080 km of coastline, the longest of any country in the world. This includes the mainland coast and offshore islands.',
      'Canada borders three oceans (Pacific, Arctic, Atlantic) plus Hudson Bay. The fractal nature of coastlines means actual measurements far exceed simple perimeter estimates.',
      'Canada borders three oceans and has thousands of islands. Coastlines are longer than they look on maps.',
      NULL,
      'Statcan / Atlas of Canada',
      'Reference',
      190000,
      220000,
      ARRAY['Canada', 'coastline', 'geography']::text[],
      'active'
    ),
(
      'What is the elevation of Mount Everest above sea level in meters?',
      8849,
      'meter',
      'meters',
      'geography',
      'easy',
      'Mount Everest has an official height of 8,849 meters (29,032 feet) above sea level, as confirmed by a 2020 joint Chinese-Nepalese survey. It is Earth''s highest mountain.',
      'A well-known reference point for altitude. Commercial aircraft cruise at ~10,000m; Everest is just below that.',
      'Commercial aircraft cruise at about 10,000 meters. Everest is just below that.',
      NULL,
      'National Geographic / Survey of Nepal',
      '2020',
      8849,
      8849,
      ARRAY['Everest', 'mountain', 'altitude', 'Nepal']::text[],
      'active'
    ),
(
      'How many rivers flow into the Amazon River?',
      1100,
      'tributary',
      'tributaries',
      'geography',
      'hard',
      'The Amazon has approximately 1,100 tributaries, of which 17 are over 1,500 km long. The river system drains 40% of South America.',
      'The Amazon basin covers ~7M km². Rivers form fractal-like networks. A major river system can have hundreds to thousands of named tributaries.',
      'The Amazon drains nearly half of South America. Major river systems have hundreds of tributaries.',
      NULL,
      'Amazon Watch / INPE',
      'Reference',
      900,
      1300,
      ARRAY['Amazon', 'river', 'tributaries', 'geography']::text[],
      'active'
    ),
(
      'How many stars are estimated to exist in the Milky Way galaxy?',
      200000000000,
      'star',
      'stars',
      'space',
      'medium',
      'The Milky Way is estimated to contain 100–400 billion stars, with 200 billion as a commonly used central estimate. This is based on measurements of galactic mass and stellar density.',
      'Gaze at a section of the Milky Way. Count stars in a small area. Extrapolate to the full 360° sphere of the galaxy. Alternatively: measure total galactic mass and divide by average stellar mass.',
      'The Milky Way is a large spiral galaxy. Typical galaxies contain tens to hundreds of billions of stars.',
      NULL,
      'NASA / ESA',
      'Reference',
      100000000000,
      400000000000,
      ARRAY['Milky Way', 'stars', 'galaxy', 'astronomy']::text[],
      'active'
    ),
(
      'What is the average distance from Earth to the Moon in kilometers?',
      384400,
      'km',
      'km',
      'space',
      'easy',
      'The average Earth-Moon distance is 384,400 km (about 60 Earth radii). It varies between ~356,500 km (perigee) and ~406,700 km (apogee).',
      'Light takes ~1.3 seconds to travel from Earth to Moon. At 300,000 km/s: 1.3 × 300,000 = 390,000 km ≈ 384,400 km.',
      'Radio signals take about 1.3 seconds to reach the Moon. Light travels ~300,000 km per second.',
      NULL,
      'NASA',
      'Reference',
      356500,
      406700,
      ARRAY['Moon', 'distance', 'Earth', 'astronomy']::text[],
      'active'
    ),
(
      'How many Earths could fit inside the Sun?',
      1300000,
      'Earth',
      'Earths',
      'space',
      'medium',
      'The Sun''s volume is approximately 1.41 × 10¹⁸ km³. Earth''s volume is ~1.08 × 10¹² km³. Ratio: ~1.3 million Earths.',
      'Sun diameter ≈ 1.39M km. Earth diameter ≈ 12,742 km. Volume ratio ≈ (1,390,000 / 12,742)³ ≈ 109³ ≈ 1.3M.',
      'The Sun''s diameter is about 109 times Earth''s diameter. Volume scales as the cube of diameter.',
      NULL,
      'NASA',
      'Reference',
      1200000,
      1400000,
      ARRAY['Sun', 'Earth', 'astronomy', 'scale']::text[],
      'active'
    ),
(
      'How many exoplanets have been confirmed by NASA as of 2023?',
      5500,
      'exoplanet',
      'exoplanets',
      'space',
      'hard',
      'NASA confirmed its 5,000th exoplanet in March 2022. By late 2023, the count had grown to over 5,500 confirmed exoplanets, with thousands more candidates awaiting confirmation.',
      'The Kepler space telescope alone found thousands of candidates. After confirmation analysis, exoplanet count has grown steadily since 1992.',
      'NASA crossed 5,000 confirmed exoplanets in 2022 and has been adding more since.',
      'https://exoplanetarchive.ipac.caltech.edu/',
      'NASA Exoplanet Archive',
      '2023',
      5000,
      6000,
      ARRAY['exoplanets', 'Kepler', 'NASA', 'astronomy']::text[],
      'active'
    ),
(
      'How long does light from the Sun take to reach Earth in minutes?',
      8.3,
      'minute',
      'minutes',
      'space',
      'easy',
      'The Sun is approximately 149.6 million km from Earth (1 AU). Light travels at ~300,000 km/s. Time = 149.6M / 300,000 ≈ 499 seconds ≈ 8.3 minutes.',
      'Distance to Sun: 150 million km. Light speed: 300,000 km/s. 150,000,000 / 300,000 = 500 seconds = 8.33 minutes.',
      'The Sun is about 150 million km away. Light travels 300,000 km per second.',
      NULL,
      'NASA',
      'Reference',
      8.2,
      8.5,
      ARRAY['Sun', 'light', 'astronomy', 'speed']::text[],
      'active'
    ),
(
      'How many moons does Saturn have?',
      146,
      'moon',
      'moons',
      'space',
      'hard',
      'Saturn has 146 confirmed moons as of 2023, making it the planet with the most known moons in the Solar System. Many were discovered with advanced telescope surveys.',
      'Saturn''s strong gravity and large size allows it to capture and retain many moons. In 2023, astronomers announced 62 new Saturnian moons, bringing the total to 146.',
      'Saturn has more moons than any other planet — far more than most people expect.',
      NULL,
      'Minor Planet Center / NASA',
      '2023',
      140,
      150,
      ARRAY['Saturn', 'moons', 'solar system', 'astronomy']::text[],
      'active'
    ),
(
      'How many light-years away is the Andromeda Galaxy?',
      2537000,
      'light-year',
      'light-years',
      'space',
      'medium',
      'The Andromeda Galaxy (M31) is approximately 2.537 million light-years from Earth. It is the nearest large spiral galaxy to the Milky Way.',
      'Andromeda is the nearest major galaxy. Its distance was measured using Cepheid variable stars. ~2.5 million light-years is the well-established value.',
      'Andromeda is the closest large galaxy to us — a couple million light-years away.',
      NULL,
      'NASA / ESA Hubble',
      'Reference',
      2500000,
      2600000,
      ARRAY['Andromeda', 'galaxy', 'distance', 'astronomy']::text[],
      'active'
    ),
(
      'How fast is the International Space Station orbiting Earth (km/h)?',
      27600,
      'km/h',
      'km/h',
      'space',
      'medium',
      'The ISS orbits Earth at approximately 27,600 km/h (7.66 km/s), completing one orbit every ~90 minutes at an altitude of about 400 km.',
      'ISS orbits at ~400 km altitude. Circumference of orbit: 2π × (6,371 + 400) km ≈ 42,600 km. Period: 90 min. Speed: 42,600 / 1.5 = 28,400 km/h ≈ 27,600 km/h.',
      'The ISS completes one orbit every 90 minutes. Earth''s circumference is ~40,000 km.',
      NULL,
      'NASA ISS',
      'Reference',
      27000,
      28500,
      ARRAY['ISS', 'orbit', 'speed', 'space station']::text[],
      'active'
    ),
(
      'How many cups of coffee are consumed in the United States every day?',
      517000000,
      'cup',
      'cups',
      'everyday',
      'easy',
      'Americans consume approximately 517 million cups of coffee per day. The US is one of the world''s largest coffee-consuming nations, with about 64% of adults drinking at least one cup daily.',
      'US population ~335M. ~65% drink coffee = ~218M coffee drinkers. Average ~2.4 cups/day: 218M × 2.4 ≈ 520M cups/day.',
      'About two-thirds of American adults drink coffee. Think about how many cups per person per day.',
      'https://www.ncausa.org/',
      'National Coffee Association',
      '2023',
      450000000,
      580000000,
      ARRAY['coffee', 'US', 'consumption', 'daily']::text[],
      'active'
    ),
(
      'How many steps does the average person walk in a year?',
      3650000,
      'step',
      'steps',
      'everyday',
      'easy',
      'The average person takes about 7,000–10,000 steps per day. At ~7,500 steps/day × 365 days = ~2.7–3.65 million steps per year.',
      'Average: 7,500 steps/day × 365 = 2,737,500. At 10,000 steps/day: 3,650,000. A typical active adult is in this range.',
      'The commonly cited goal is 10,000 steps per day. Most people do slightly less.',
      NULL,
      'CDC / Pedometer research',
      'Reference',
      2500000,
      4000000,
      ARRAY['walking', 'steps', 'health', 'exercise']::text[],
      'active'
    ),
(
      'How many hours does the average American spend watching TV per week?',
      28,
      'hour',
      'hours',
      'everyday',
      'easy',
      'The average American watches approximately 28 hours of TV per week (~4 hours/day), according to Nielsen data. This includes live TV, DVR, and streaming on TV sets.',
      'If average viewing is ~4 hours per day: 4 × 7 = 28 hours per week. This aligns with Nielsen data.',
      'Think about how many hours per day the average American might watch TV or streaming.',
      NULL,
      'Nielsen',
      '2023',
      20,
      35,
      ARRAY['TV', 'media', 'US', 'entertainment']::text[],
      'active'
    ),
(
      'How many times does a person blink in a day?',
      17000,
      'blink',
      'blinks',
      'everyday',
      'easy',
      'The average person blinks approximately 15–20 times per minute. At 17 blinks/min × 960 waking minutes = ~16,320 blinks per day ≈ 17,000.',
      'Average blink rate: ~17 blinks/min. Waking hours: ~16 hrs = 960 min. 17 × 960 = 16,320 ≈ 17,000.',
      'You blink about 15–20 times per minute. How many minutes are you awake each day?',
      NULL,
      'Ophthalmology research',
      'Reference',
      14000,
      20000,
      ARRAY['blink', 'human body', 'biology', 'everyday']::text[],
      'active'
    ),
(
      'How many plastic bags are used worldwide every minute?',
      2000000,
      'bag',
      'bags',
      'everyday',
      'medium',
      'Approximately 1–5 million plastic bags are used every minute worldwide. A commonly cited figure is around 2 million per minute, or about 1 trillion per year.',
      'World uses ~1 trillion plastic bags/year. ÷ 365 ÷ 24 ÷ 60 = ~1.9M per minute ≈ 2M per minute.',
      'The world uses roughly 1 trillion plastic bags per year. Divide that down to per minute.',
      NULL,
      'UNEP / Earth Policy Institute',
      'Reference',
      1000000,
      5000000,
      ARRAY['plastic', 'environment', 'bags', 'waste']::text[],
      'active'
    ),
(
      'How many hours does the average person spend sleeping in their lifetime?',
      230000,
      'hour',
      'hours',
      'everyday',
      'easy',
      'At 8 hours of sleep per night over 79 years: 8 × 365 × 79 = 230,680 hours ≈ 230,000 hours of sleep in a lifetime.',
      '8 hours/night × 365 nights/year × 79 years = 230,680 hours.',
      'How many hours do you sleep per night? Multiply by days in a lifetime.',
      NULL,
      'Calculation',
      'Reference',
      200000,
      270000,
      ARRAY['sleep', 'lifetime', 'health', 'biology']::text[],
      'active'
    ),
(
      'How many photos are taken worldwide every day?',
      1800000000,
      'photo',
      'photos',
      'everyday',
      'medium',
      'Approximately 1.8 trillion photos are taken per year, or roughly 4.7–5 billion per day. Smartphones have dramatically increased photo volume. Some estimates place this higher, at 1.4–1.8 trillion per year.',
      '~5B smartphone users. If each takes ~1 photo/day on average: 5B photos/day. Accounting for non-smartphone photographers and events: 1.4–1.8 billion is a conservative estimate.',
      'There are ~5 billion smartphone users. Even if each takes one photo every few days, that''s a lot.',
      NULL,
      'Mylio / InfoTrends',
      '2023',
      1000000000,
      5000000000,
      ARRAY['photography', 'smartphone', 'photos', 'digital']::text[],
      'active'
    ),
(
      'How many times does a human breathe in a lifetime?',
      672000000,
      'breath',
      'breaths',
      'everyday',
      'easy',
      'Average breathing rate is ~16 breaths per minute. Over 79 years awake (some variation during sleep): 16 × 60 × 24 × 365 × 79 ≈ 665 million breaths.',
      '16 breaths/min × 60 min/hr × 24 hr/day × 365 days/yr × 79 years = 665,625,600 ≈ 670 million.',
      'You breathe about 15–20 times per minute. How many minutes are in 79 years?',
      NULL,
      'Calculation',
      'Reference',
      600000000,
      750000000,
      ARRAY['breathing', 'human body', 'biology', 'lifetime']::text[],
      'active'
    ),
(
      'How many chickens are slaughtered for food worldwide every year?',
      70000000000,
      'chicken',
      'chickens',
      'food',
      'medium',
      'Approximately 70 billion chickens are slaughtered for food annually worldwide. This figure comes from FAO livestock data. Poultry is the most consumed meat globally.',
      'World population ~8B. If average person eats ~10 kg of chicken/year and a chicken weighs ~2kg: 8B × 10 / 2 = 40B. Accounting for waste and non-average consumption, ~70B is the industry figure.',
      'The world population is 8 billion. Think about how often the average person eats chicken.',
      'https://www.fao.org/faostat/',
      'FAO',
      '2021',
      65000000000,
      75000000000,
      ARRAY['chicken', 'meat', 'food', 'agriculture']::text[],
      'active'
    ),
(
      'How many pizzas are sold in the United States every year?',
      3000000000,
      'pizza',
      'pizzas',
      'food',
      'medium',
      'Americans consume approximately 3 billion pizzas per year, or roughly 23 pounds of pizza per person annually. The US pizza market generates about $46 billion in sales.',
      'US population: 335M. If average person eats pizza once a week: 335M × 52 = 17.4B slices. Assuming ~8 slices per pizza: 17.4B / 8 = 2.2B. Accounting for larger orders: ~3B.',
      'Pizza is eaten weekly or more by many Americans. Work from population and frequency.',
      NULL,
      'PMQ Pizza Magazine',
      'Reference',
      2000000000,
      4000000000,
      ARRAY['pizza', 'food', 'US', 'consumption']::text[],
      'active'
    ),
(
      'How many cups of tea are consumed worldwide every day?',
      3000000000,
      'cup',
      'cups',
      'food',
      'medium',
      'Approximately 3 billion cups of tea are drunk every day worldwide. Tea is the second most popular beverage after water. Major consumers include China, India, and the UK.',
      'World: 8B people. China alone has 1.4B people with high tea consumption. India, UK, Turkey, and many other cultures drink significant quantities. Average ~0.4 cups/person/day globally: 8B × 0.4 = 3.2B.',
      'Tea is the most consumed beverage after water. Think about Asia, where most tea is drunk.',
      NULL,
      'Tea Association / Statista',
      'Reference',
      2000000000,
      5000000000,
      ARRAY['tea', 'beverage', 'consumption', 'global']::text[],
      'active'
    ),
(
      'How many McDonald''s restaurants are there worldwide?',
      40000,
      'restaurant',
      'restaurants',
      'food',
      'easy',
      'McDonald''s operates approximately 40,000 restaurants in over 100 countries as of 2023. It serves about 69 million customers daily.',
      'McDonald''s is in ~100 countries. Average ~400 per country (though heavily skewed to the US with ~14,000). Total ≈ 40,000.',
      'McDonald''s is the world''s largest fast food chain by number of locations.',
      NULL,
      'McDonald''s Annual Report',
      '2023',
      38000,
      42000,
      ARRAY['McDonald''s', 'fast food', 'restaurants', 'global']::text[],
      'active'
    ),
(
      'How many bananas are produced worldwide every year (in tonnes)?',
      120000000,
      'tonne',
      'tonnes',
      'food',
      'hard',
      'Global banana production is approximately 120 million tonnes per year. Bananas are the world''s fourth largest agricultural product by value.',
      'World: 8B people. If average person eats ~15kg of bananas/year: 8B × 15kg = 120M tonnes. This aligns with FAO data.',
      'Think about how often people eat bananas globally and how much they weigh.',
      'https://www.fao.org/faostat/',
      'FAO',
      '2021',
      110000000,
      130000000,
      ARRAY['bananas', 'food', 'agriculture', 'production']::text[],
      'active'
    ),
(
      'How many calories does the average American consume per day?',
      3600,
      'calorie',
      'calories',
      'food',
      'easy',
      'Americans consume approximately 3,600 calories per day on average (based on food supply data), which is above the recommended intake of 2,000–2,500 calories. This includes waste and unreported consumption.',
      'Recommended intake: 2,000–2,500 cal. Americans tend to over-consume. Food supply data (production - exports + imports) divided by population ≈ 3,600 cal/day.',
      'The recommended daily intake is about 2,000 calories, but Americans typically exceed this.',
      NULL,
      'USDA / CDC',
      'Reference',
      3000,
      4000,
      ARRAY['calories', 'food', 'US', 'nutrition']::text[],
      'active'
    ),
(
      'How many liters of Coca-Cola are consumed worldwide every day?',
      2000000000,
      'serving (8oz)',
      'servings (8oz)',
      'food',
      'medium',
      'Coca-Cola reports approximately 2 billion servings consumed per day across all its brands worldwide. A standard serving is 8 oz (240ml).',
      'Coca-Cola has operations in ~200 countries. World: 8B people. If 1 in 4 people drinks one serving every day: 2B servings/day. Aligns with Coca-Cola''s own reporting.',
      'Coca-Cola publishes this number. Think about how many people drink a Coke-brand product daily.',
      NULL,
      'The Coca-Cola Company',
      'Reference',
      1500000000,
      2500000000,
      ARRAY['Coca-Cola', 'beverages', 'consumption', 'global']::text[],
      'active'
    ),
(
      'How many ants are estimated to live on Earth?',
      20000000000000000,
      'ant',
      'ants',
      'animals',
      'unhinged',
      'A 2022 study in PNAS estimated there are approximately 20 quadrillion (20×10¹⁵) ants on Earth. Their collective biomass (roughly 12 megatons of carbon) exceeds that of all wild birds and mammals combined.',
      'Ants are found on every continent except Antarctica. Tropical regions have enormous ant densities. Scientific census methods applied to different biomes, then extrapolated to global land area.',
      'Ants are on every continent and exist in astronomical numbers — far more than humans.',
      'https://www.pnas.org/doi/10.1073/pnas.2201550119',
      'Schultheiss et al., PNAS 2022',
      '2022',
      10000000000000000,
      30000000000000000,
      ARRAY['ants', 'insects', 'global', 'population']::text[],
      'active'
    ),
(
      'How many domestic cats are estimated to exist worldwide?',
      600000000,
      'cat',
      'cats',
      'animals',
      'medium',
      'There are approximately 600 million domestic cats worldwide, including owned and feral cats. The US alone has ~90 million owned cats and an estimated 30–80 million feral cats.',
      '~1.4B households worldwide. If ~25% have at least one cat: 350M cat-owning households × ~1.5 cats = 525M owned. Add feral cats: total ~600M.',
      'Think about the fraction of households that own a cat and how many cats per household.',
      NULL,
      'World Animal Foundation estimates',
      'Reference',
      400000000,
      700000000,
      ARRAY['cats', 'pets', 'animals', 'global']::text[],
      'active'
    ),
(
      'How many species of birds are known to exist?',
      10000,
      'species',
      'species',
      'animals',
      'medium',
      'There are approximately 10,000–10,700 recognized bird species in the world, depending on the taxonomic classification used. New species are occasionally described.',
      'Birds are well-catalogued compared to insects or marine life. Ornithologists have systematically documented species globally. The total is ~10,000 with minor variation by authority.',
      'Birds are well-studied. There are roughly as many bird species as years in recorded human history.',
      NULL,
      'Clements Checklist / IOC World Bird List',
      '2023',
      9500,
      11000,
      ARRAY['birds', 'species', 'biodiversity', 'ornithology']::text[],
      'active'
    ),
(
      'How many blue whales are estimated to exist in the world''s oceans?',
      15000,
      'whale',
      'whales',
      'animals',
      'hard',
      'Blue whale populations were devastated by commercial whaling. Current estimates suggest 10,000–25,000 blue whales remain, with ~15,000 as a central estimate. They are listed as endangered.',
      'Population surveys use acoustic monitoring, sighting surveys, and genetic analysis. Recovery has been slow since whaling ended.',
      'Blue whales were almost hunted to extinction. Numbers are recovering but still very low.',
      NULL,
      'IUCN / WWF',
      '2023',
      10000,
      25000,
      ARRAY['blue whale', 'conservation', 'ocean', 'endangered']::text[],
      'active'
    ),
(
      'How many emperor penguins are estimated to live in Antarctica?',
      600000,
      'penguin',
      'penguins',
      'animals',
      'hard',
      'Emperor penguin populations are estimated at approximately 595,000–648,000 individuals, based on satellite imagery surveys of their colonies on sea ice.',
      'Satellite surveys identify breeding colonies by their guano stains on ice. There are ~54 known colonies. Average colony size × 54 colonies gives total population.',
      'Emperor penguin colonies in Antarctica can be counted from satellite images.',
      'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4872527/',
      'Fretwell et al. 2012 / updated surveys',
      'Reference',
      500000,
      700000,
      ARRAY['penguin', 'Antarctica', 'wildlife', 'conservation']::text[],
      'active'
    ),
(
      'How many domestic dogs are there worldwide?',
      900000000,
      'dog',
      'dogs',
      'animals',
      'medium',
      'There are approximately 900 million dogs worldwide, including ~500 million stray and free-roaming dogs. The WHO estimates ~200 million stray dogs.',
      '~500M dogs in homes. ~400M free-roaming/stray. Many countries have high stray dog populations. Total: ~900M.',
      'Dogs are the world''s most popular pet. Consider both owned pets and the many stray dogs in developing countries.',
      NULL,
      'WHO / World Animal Protection',
      'Reference',
      700000000,
      1000000000,
      ARRAY['dogs', 'pets', 'animals', 'global']::text[],
      'active'
    ),
(
      'What is Apple''s annual revenue in US dollars (2023 fiscal year)?',
      383000000000,
      'USD',
      'USD',
      'business',
      'medium',
      'Apple reported revenue of approximately $383 billion for fiscal year 2023 (ending September 2023), down slightly from $394B in FY2022.',
      'Apple sells ~220M iPhones/year at avg ~$800 = $176B just from iPhone. Mac, iPad, wearables, services add more. Services alone is ~$80B. Total around $380–400B.',
      'Apple sells ~220 million iPhones per year at $800 average price. iPhone is only about half their revenue.',
      NULL,
      'Apple Annual Report FY2023',
      'FY2023',
      375000000000,
      395000000000,
      ARRAY['Apple', 'revenue', 'business', 'tech']::text[],
      'active'
    ),
(
      'How many employees does Amazon have worldwide?',
      1460000,
      'employee',
      'employees',
      'business',
      'medium',
      'Amazon employs approximately 1.46 million people worldwide as of 2023, making it one of the world''s largest employers. This includes warehouse workers, delivery drivers, and corporate employees.',
      'Amazon has hundreds of fulfillment centers worldwide, each employing 1,000–5,000 workers. Plus corporate, AWS, Whole Foods, and logistics. Total is well over 1 million.',
      'Amazon has hundreds of fulfillment centers and millions of packages shipped daily — consider the workforce needed.',
      NULL,
      'Amazon Annual Report 2023',
      '2023',
      1300000,
      1600000,
      ARRAY['Amazon', 'employees', 'workforce', 'business']::text[],
      'active'
    ),
(
      'How many packages does FedEx deliver per day worldwide?',
      17000000,
      'package',
      'packages',
      'business',
      'medium',
      'FedEx delivers approximately 17 million packages per day across its global network, serving 220+ countries.',
      'FedEx annual volume: ~6.5B packages/year ÷ 365 ≈ 17.8M/day.',
      'FedEx serves 220+ countries. Think about how many packages a major global logistics company handles.',
      NULL,
      'FedEx Annual Report',
      '2023',
      15000000,
      20000000,
      ARRAY['FedEx', 'logistics', 'shipping', 'business']::text[],
      'active'
    ),
(
      'What is the market capitalization of Microsoft in USD (approximate, 2023)?',
      2500000000000,
      'USD',
      'USD',
      'business',
      'hard',
      'Microsoft''s market capitalization reached approximately $2.5 trillion in 2023, making it one of the most valuable companies in the world alongside Apple and NVIDIA.',
      'Microsoft revenue ~$200B. Tech companies can trade at 10–15× revenue. $200B × 12 = $2.4T. Also comparable: Apple ~$3T, Alphabet ~$1.7T.',
      'Microsoft is one of the world''s top 3 most valuable companies. Apple is worth about $3 trillion.',
      NULL,
      'Bloomberg / Yahoo Finance',
      '2023',
      2000000000000,
      3000000000000,
      ARRAY['Microsoft', 'market cap', 'business', 'stocks']::text[],
      'active'
    ),
(
      'How many Starbucks stores are there worldwide?',
      36000,
      'store',
      'stores',
      'business',
      'easy',
      'Starbucks operates approximately 36,000 stores in 80+ countries as of 2023. China is its second-largest market after the US.',
      'US has ~16,000 Starbucks. International adds ~20,000. Total ~36,000.',
      'Starbucks is the world''s largest coffee chain. Think about how many cities have multiple locations.',
      NULL,
      'Starbucks Annual Report',
      '2023',
      34000,
      38000,
      ARRAY['Starbucks', 'coffee', 'retail', 'business']::text[],
      'active'
    ),
(
      'What is the global revenue of the video game industry in USD per year?',
      183000000000,
      'USD',
      'USD',
      'business',
      'medium',
      'The global video game industry generated approximately $183 billion in revenue in 2023, making it larger than the global film and music industries combined.',
      '~3.2B gamers worldwide. Average spending: mobile gamers spend less, console/PC gamers more. Average ~$57/gamer/year: 3.2B × $57 ≈ $182B.',
      'There are about 3 billion gamers worldwide. Consider average spending across mobile, PC, and console.',
      NULL,
      'Newzoo Global Games Market Report',
      '2023',
      160000000000,
      200000000000,
      ARRAY['gaming', 'business', 'revenue', 'entertainment']::text[],
      'active'
    ),
(
      'How many credit card transactions are processed globally every day?',
      110000000,
      'transaction',
      'transactions',
      'business',
      'hard',
      'Approximately 110 million credit card transactions are processed per day globally (by Visa, Mastercard, and other networks). Visa alone processes ~700 transactions per second.',
      'Visa: ~700 tx/sec × 86,400 sec/day = 60.5M/day. Mastercard: similar volume. Others add more. Total across all networks: ~100–150M/day.',
      'Visa alone processes about 700 transactions per second. There are multiple card networks globally.',
      NULL,
      'Visa / Mastercard investor reports',
      'Reference',
      80000000,
      150000000,
      ARRAY['credit cards', 'finance', 'payments', 'business']::text[],
      'active'
    ),
(
      'How many people died in World War II (estimated total)?',
      70000000,
      'person',
      'people',
      'history',
      'medium',
      'World War II caused between 70 and 85 million deaths, including military casualties, civilian deaths, and Holocaust victims. It is the deadliest conflict in human history.',
      'Military deaths: ~25M. Soviet civilian deaths: ~15M. Chinese civilian deaths: ~8–20M. Other civilian deaths add millions more. Total: 70–85M.',
      'WWII was the deadliest conflict in history — far deadlier than WWI. Think about the scale of the Soviet and Chinese civilian casualties.',
      NULL,
      'Various historical sources; ranges disputed',
      '1939–1945',
      70000000,
      85000000,
      ARRAY['WWII', 'war', 'history', 'casualties']::text[],
      'active'
    ),
(
      'How many years ago did the first homo sapiens appear on Earth?',
      300000,
      'year',
      'years',
      'history',
      'medium',
      'The earliest known Homo sapiens fossils date to approximately 300,000 years ago, from Jebel Irhoud, Morocco. This revised the earlier estimate of ~200,000 years.',
      'Fossil evidence and mitochondrial DNA studies suggest Homo sapiens emerged in Africa approximately 300,000 years ago.',
      'Human fossils found in Morocco changed the scientific consensus on when Homo sapiens appeared.',
      'https://www.nature.com/articles/nature22336',
      'Hublin et al., Nature 2017',
      'Reference',
      280000,
      350000,
      ARRAY['evolution', 'human history', 'paleontology']::text[],
      'active'
    ),
(
      'How many books did Gutenberg''s printing press produce in the first 50 years after its invention (approximately)?',
      20000000,
      'book',
      'books',
      'history',
      'hard',
      'Historians estimate that between 8 million and 20 million books (incunabula) were printed in Europe by 1500, within about 50 years of Gutenberg''s press (~1450). Some estimates go higher.',
      'By 1500, ~1,000 printing shops existed in Europe. If each produced ~100 books/year: 1,000 × 100 × 50 years = 5M. But press runs were larger — estimates range 8–20M.',
      'Within 50 years, printing had spread across Europe with hundreds of printing shops.',
      NULL,
      'Eisenstein ''The Printing Revolution''',
      '1450–1500',
      8000000,
      20000000,
      ARRAY['Gutenberg', 'printing', 'books', 'history']::text[],
      'active'
    ),
(
      'How many soldiers fought in the Battle of the Somme (total, both sides)?',
      3000000,
      'soldier',
      'soldiers',
      'history',
      'hard',
      'The Battle of the Somme (1916) involved approximately 3 million soldiers from both the Allied and German sides over its 141-day duration. It resulted in over 1 million casualties.',
      'British forces: ~1.5M committed over the battle. French: ~400K. German: ~1.2M. Total: ~3M across all sides.',
      'The Somme was one of the largest battles in history, lasting over 4 months in 1916.',
      NULL,
      'Imperial War Museum / Military historians',
      '1916',
      2000000,
      4000000,
      ARRAY['WWI', 'Somme', 'military', 'history']::text[],
      'active'
    ),
(
      'How many pyramids are estimated to exist in Egypt?',
      138,
      'pyramid',
      'pyramids',
      'history',
      'medium',
      'Egypt has approximately 118–138 identified pyramids. The famous Giza complex has 3 large pyramids, but there are many smaller pyramids built by various pharaohs.',
      'Ancient Egypt lasted ~3,000 years with many pharaohs. Each had a burial monument. Many smaller or eroded pyramids exist beyond the famous Giza examples.',
      'There are far more Egyptian pyramids than just the famous ones at Giza.',
      NULL,
      'Ministry of Antiquities, Egypt',
      'Reference',
      118,
      138,
      ARRAY['Egypt', 'pyramids', 'archaeology', 'history']::text[],
      'active'
    ),
(
      'How many people watched the 2022 FIFA World Cup Final globally?',
      1500000000,
      'viewer',
      'viewers',
      'sports',
      'medium',
      'The 2022 FIFA World Cup Final (Argentina vs France) was watched by approximately 1.5 billion viewers worldwide, making it one of the most watched sporting events in history.',
      'World Cup Final is the world''s biggest sporting event. World population ~8B. Excluding young children and regions without TV access, perhaps 3B potential viewers. Significant fraction tune in: ~1.5B.',
      'The World Cup Final is the single most-watched sporting event. Billions of people follow football.',
      NULL,
      'FIFA',
      '2022',
      1000000000,
      2000000000,
      ARRAY['FIFA', 'World Cup', 'football', 'viewers']::text[],
      'active'
    ),
(
      'How many official FIFA footballs (size 5) are manufactured every year globally?',
      40000000,
      'football',
      'footballs',
      'sports',
      'hard',
      'Approximately 40 million footballs (size 5) are manufactured worldwide each year. The vast majority come from Sialkot, Pakistan, which produces ~70% of the world''s hand-stitched footballs.',
      '~300M football players worldwide. If average player buys one ball every 5–7 years: 300M / 6 = 50M. Accounting for team supply, school, and recreational use, ~40M is a reasonable estimate.',
      'There are roughly 300 million football players globally. How often does a player need a new ball?',
      NULL,
      'FIFA / Industry estimates',
      'Reference',
      30000000,
      60000000,
      ARRAY['football', 'manufacturing', 'sports', 'FIFA']::text[],
      'active'
    ),
(
      'How many miles does an NBA player run during a typical season?',
      490,
      'mile',
      'miles',
      'sports',
      'hard',
      'NBA players run approximately 3–5 miles per game. Over an 82-game regular season at ~3.5 miles/game: 82 × 3.5 ≈ 287 miles in games. Including practice and playoffs, total is ~400–600 miles per season.',
      'Distance per game: ~3 miles for most players. 82 regular season games: 82 × 3 = 246 miles. Training and playoffs add ~50%. Total: ~400–600 miles.',
      'Think about how far players run per game and how many games are in an NBA season.',
      NULL,
      'NBA tracking data (Second Spectrum)',
      'Reference',
      350,
      650,
      ARRAY['NBA', 'basketball', 'sports', 'running']::text[],
      'active'
    ),
(
      'How many official tennis balls are used at Wimbledon each year?',
      54000,
      'tennis ball',
      'tennis balls',
      'sports',
      'hard',
      'Wimbledon uses approximately 54,000 tennis balls per year. Balls are changed every 7 games in matches, requiring a large supply for the tournament.',
      'Wimbledon has ~650 matches. Each match uses ~100 balls (changed every 7 games). 650 × 100 ≈ 65,000. Official figure is ~54,000 due to shorter matches.',
      'Tennis balls are changed every 7–9 games. Think about how many matches Wimbledon has.',
      NULL,
      'All England Club',
      'Reference',
      48000,
      60000,
      ARRAY['Wimbledon', 'tennis', 'sports', 'equipment']::text[],
      'active'
    ),
(
      'How many registered golfers are there in the United States?',
      26000000,
      'golfer',
      'golfers',
      'sports',
      'medium',
      'The US has approximately 26 million golfers (defined as playing at least one round per year). Golf is one of the most popular participation sports in America.',
      'US population: 335M. Golf is accessible to adults mainly. ~100M adults over 18 who might play. If ~26% play at least once/year: 26M.',
      'Golf is one of the most popular participation sports in the US. Think about what fraction of Americans play.',
      NULL,
      'National Golf Foundation',
      '2023',
      22000000,
      30000000,
      ARRAY['golf', 'sports', 'US', 'participation']::text[],
      'active'
    ),
(
      'How many calories does a Tour de France cyclist burn per stage on average?',
      6000,
      'calorie',
      'calories',
      'sports',
      'medium',
      'Tour de France cyclists burn approximately 5,000–8,000 calories per stage depending on the stage type and terrain. Mountain stages can exceed 9,000 calories.',
      'Cycling at race pace burns ~600–900 cal/hour. Average stage: 5–7 hours. 750 × 6 = 4,500. Add basal metabolic rate and shorter/longer stages: ~6,000 average.',
      'Elite cyclists burn about 700–900 calories per hour. Tour stages average 5–7 hours.',
      NULL,
      'Sports science research / Tour de France nutrition data',
      'Reference',
      5000,
      8000,
      ARRAY['Tour de France', 'cycling', 'sports', 'nutrition']::text[],
      'active'
    ),
(
      'How many trees are on Earth?',
      3000000000000,
      'tree',
      'trees',
      'nature',
      'hard',
      'A 2015 study in Nature estimated approximately 3 trillion trees on Earth. This revised earlier estimates of 400 billion upward by nearly 8×, using new satellite and forest survey data.',
      'Global forested area: ~40M km². Average tree density in forests: ~400 trees/hectare. 40M km² × 100 ha/km² × 400 = 1.6 trillion. Including sparse woodland: ~3 trillion.',
      'A 2015 Nature study dramatically revised earlier estimates upward. Think in trillions.',
      'https://www.nature.com/articles/nature14967',
      'Crowther et al., Nature 2015',
      '2015',
      2500000000000,
      3500000000000,
      ARRAY['trees', 'forests', 'nature', 'environment']::text[],
      'active'
    ),
(
      'How many lightning strikes hit Earth''s surface every day?',
      8000000,
      'lightning strike',
      'lightning strikes',
      'nature',
      'medium',
      'Earth experiences approximately 8 million lightning strikes per day (about 100 per second). Most strikes occur over land, particularly in tropical regions.',
      '~100 lightning bolts/second × 60 sec × 60 min × 24 hr = 8.64 million strikes/day ≈ 8M.',
      'Lightning strikes happen about 100 times per second globally. Convert to daily totals.',
      NULL,
      'NASA / NOAA',
      'Reference',
      6000000,
      10000000,
      ARRAY['lightning', 'weather', 'nature', 'atmosphere']::text[],
      'active'
    ),
(
      'How many tonnes of plastic enter the ocean every year?',
      8000000,
      'tonne',
      'tonnes',
      'nature',
      'medium',
      'An estimated 8–14 million tonnes of plastic enter the ocean annually, based on research by Jambeck et al. (2015). This has likely increased since that study.',
      '~8B people globally. Plastic waste per person: ~50kg/year. Mismanaged: ~30% in coastal regions: 8B × 50kg × 0.3 × (fraction reaching ocean) = millions of tonnes.',
      'Think about how much plastic is produced and what fraction is mismanaged in coastal regions.',
      'https://www.science.org/doi/10.1126/science.1260352',
      'Jambeck et al., Science 2015',
      '2015',
      8000000,
      14000000,
      ARRAY['plastic', 'ocean', 'pollution', 'environment']::text[],
      'active'
    ),
(
      'How many earthquakes occur on Earth every year?',
      500000,
      'earthquake',
      'earthquakes',
      'nature',
      'medium',
      'Approximately 500,000 earthquakes per year are detected by seismographs globally. Of these, about 100,000 can be felt, and ~100 cause damage.',
      'USGS data: ~500,000 detectable earthquakes/year. Most are minor tremors. Major quakes (M7+): ~17/year. M8+: ~1/year.',
      'Seismographs detect thousands of earthquakes per day. Most are too small to feel.',
      NULL,
      'USGS',
      'Reference',
      400000,
      600000,
      ARRAY['earthquakes', 'geology', 'nature', 'seismology']::text[],
      'active'
    ),
(
      'How many tonnes of CO₂ are emitted globally every year?',
      37000000000,
      'tonne',
      'tonnes',
      'nature',
      'medium',
      'Global CO₂ emissions from fossil fuels and industry are approximately 37 billion tonnes per year as of 2023, based on Global Carbon Project data.',
      'World uses ~580 EJ of energy/year. Fossil fuels: ~80%. CO₂ from fossil combustion: ~34B tonnes. Land use change adds ~3B tonnes. Total: ~37B tonnes.',
      'Think about world energy use and the fact that burning fossil fuels emits CO₂. Global emissions are measured in billions of tonnes.',
      'https://www.globalcarbonproject.org/',
      'Global Carbon Project',
      '2023',
      35000000000,
      40000000000,
      ARRAY['CO2', 'emissions', 'climate', 'environment']::text[],
      'active'
    ),
(
      'If all the blood vessels in a human body were laid end to end, how many times would they circle Earth?',
      2.5,
      'time',
      'times',
      'absurd',
      'unhinged',
      'The total length of blood vessels in a human body is approximately 100,000 km. Earth''s circumference is ~40,075 km. 100,000 / 40,075 ≈ 2.5 times around Earth.',
      'Human body has ~60,000 miles (100,000 km) of blood vessels including capillaries. Earth circumference: 40,075 km. 100,000 / 40,075 ≈ 2.5 times.',
      'The total length of human blood vessels is around 100,000 km. Earth''s circumference is about 40,000 km.',
      NULL,
      'Biology reference / KidsHealth',
      'Reference',
      2,
      3,
      ARRAY['human body', 'blood vessels', 'biology', 'scale']::text[],
      'active'
    ),
(
      'How many piano tuners are there in Chicago? (A classic Fermi question)',
      125,
      'piano tuner',
      'piano tuners',
      'absurd',
      'unhinged',
      'Fermi''s classic estimate: Chicago population ~3M. ~1 piano per 20 households = 3M/3 households/person × 1/20 = ~50,000 pianos. Each tuned once a year. Tuner works ~250 days × 4 pianos/day = 1,000 pianos/year. 50,000/1,000 = 50–125 tuners.',
      '1. Population → households → pianos. 2. Tuning frequency. 3. Tuner capacity. This is Fermi''s own famous example.',
      'How many pianos are in Chicago? How often are they tuned? How many can one tuner service per year?',
      NULL,
      'Fermi''s original problem',
      'Reference',
      50,
      250,
      ARRAY['Fermi', 'classic', 'Chicago', 'estimation']::text[],
      'active'
    ),
(
      'How many golf balls would fit in a school bus?',
      500000,
      'golf ball',
      'golf balls',
      'absurd',
      'unhinged',
      'A school bus interior is roughly 2.4m × 2m × 6m = 28.8 m³. A golf ball has diameter 4.27 cm, volume = 40.7 cm³. With ~64% packing efficiency: 28.8M cm³ × 0.64 / 40.7 cm³ ≈ 452,000. Often rounded to ~500,000.',
      'Bus volume: ~30 cubic meters. Golf ball: diameter ~4.3cm, volume ~41 cm³. Packing efficiency ~64%: 30,000,000 cm³ × 0.64 / 41 ≈ 468,000.',
      'Start with the bus interior volume in cubic centimeters, then divide by golf ball volume with a packing factor.',
      NULL,
      'Classic interview question / calculation',
      'Reference',
      300000,
      700000,
      ARRAY['golf ball', 'school bus', 'volume', 'Fermi']::text[],
      'active'
    ),
(
      'How many people are airborne (in a plane) at any given moment globally?',
      1200000,
      'person',
      'people',
      'absurd',
      'hard',
      'At any given moment, approximately 1–1.2 million people are in the air. This is based on ~100,000 commercial flights daily, each averaging ~180 passengers, divided by average flight time of ~3 hours.',
      '100,000 flights/day. Average 180 passengers. Average flight: 2.5 hours. At any moment: 100,000 × 180 × (2.5/24) = 1,875,000. But not all flights carry full loads: ~1.2M.',
      'Think about how many flights are in the air simultaneously and how many passengers each carries.',
      NULL,
      'FlightAware / ICAO',
      '2023',
      900000,
      1500000,
      ARRAY['aviation', 'planes', 'airborne', 'transportation']::text[],
      'active'
    ),
(
      'If you stacked all the iPhones ever sold on top of each other, how tall would the stack be in kilometers?',
      169050,
      'km',
      'km',
      'absurd',
      'unhinged',
      '~2.3 billion iPhones sold. Average iPhone thickness: ~7.35mm. 2,300,000,000 × 0.00735 km = 16,905,000 km. Wait — that''s 16.9 million km. Roughly 44 times the distance to the Moon.',
      '2.3B iPhones × 7.35mm = 16.9 million km. The stack would reach the Moon ~44 times. This answer uses 2.3B × 0.00735m / 1000 km = 16,905 km... actually 16,905,000 km.',
      'Start with total iPhones sold (~2.3 billion) and multiply by the thickness of an iPhone.',
      NULL,
      'Apple sales data / calculation',
      '2007–2023',
      10000000,
      25000000,
      ARRAY['iPhone', 'Apple', 'stacking', 'scale', 'absurd']::text[],
      'active'
    ),
(
      'How many seconds old is someone who just turned 30 years old?',
      946080000,
      'second',
      'seconds',
      'absurd',
      'medium',
      '30 years × 365.25 days/year × 24 hours × 60 minutes × 60 seconds = 946,080,000 seconds ≈ 946 million seconds.',
      '30 × 365.25 × 86,400 = 946,728,000. A 30-year-old is just under 1 billion seconds old.',
      'How many seconds are in a year? Multiply by 30.',
      NULL,
      'Calculation',
      'Reference',
      946080000,
      946728000,
      ARRAY['time', 'age', 'seconds', 'calculation']::text[],
      'active'
    ),
(
      'How much would it cost in electricity (USD) to charge an iPhone 15 for a full year, every night?',
      1,
      'USD',
      'USD',
      'absurd',
      'easy',
      'iPhone 15 battery: 3,349 mAh at 3.86V = ~12.9 Wh. Charging once/night for a year: 12.9 × 365 = 4,709 Wh = 4.71 kWh. At US average $0.17/kWh: 4.71 × $0.17 = $0.80. Less than $1/year.',
      'Battery capacity ~13 Wh. Nightly: 13 × 365 = 4,745 Wh = 4.7 kWh/year. US electricity ~$0.17/kWh. 4.7 × $0.17 ≈ $0.80.',
      'iPhone batteries are tiny — about 13 watt-hours. How much does 1 kWh of electricity cost?',
      NULL,
      'Apple tech specs / EIA electricity rates',
      '2023',
      0.5,
      2,
      ARRAY['iPhone', 'electricity', 'energy', 'cost']::text[],
      'active'
    ),
(
      'How many kilometers of road exist in the United States?',
      6700000,
      'km',
      'km',
      'infrastructure',
      'medium',
      'The US has approximately 6.7 million km of roads, including Interstate highways, US routes, state roads, local roads, and private roads.',
      'US area: 9.8M km². If roads were on a 1km grid across half the country: 9.8M / 2 × 2 (two directions) ≈ too high. Bottom up: ~50,000 km interstate + millions of local roads = ~6.7M km total.',
      'The US is huge with roads everywhere — including small local roads, driveways, and highways.',
      NULL,
      'US Department of Transportation',
      'Reference',
      6000000,
      7000000,
      ARRAY['roads', 'US', 'infrastructure', 'transportation']::text[],
      'active'
    ),
(
      'How many airports exist in the United States?',
      19700,
      'airport',
      'airports',
      'infrastructure',
      'medium',
      'The FAA lists approximately 19,700 airports in the US, including commercial airports, general aviation airports, seaplane bases, and heliports.',
      '~400 commercial airports. But the US has thousands of small regional and private airstrips. FAA tracks all of them: ~19,700 total.',
      'The US has far more airports than commercial ones — include small general aviation airstrips.',
      NULL,
      'FAA Airport Data',
      'Reference',
      18000,
      21000,
      ARRAY['airports', 'aviation', 'US', 'infrastructure']::text[],
      'active'
    ),
(
      'How many shipping containers are in use worldwide?',
      50000000,
      'container',
      'containers',
      'infrastructure',
      'hard',
      'There are approximately 50 million shipping containers in use globally. The standard TEU (Twenty-foot Equivalent Unit) container is the industry standard.',
      'Global container shipping trades ~250M TEU per year. Containers cycle ~5 times/year: 250M / 5 = 50M containers in existence.',
      'Think about how many container ships there are and how many containers each carries per year.',
      NULL,
      'World Shipping Council',
      'Reference',
      40000000,
      65000000,
      ARRAY['shipping', 'containers', 'trade', 'infrastructure']::text[],
      'active'
    ),
(
      'How many oil barrels does the world consume per day?',
      100000000,
      'barrel',
      'barrels',
      'infrastructure',
      'medium',
      'Global oil consumption is approximately 100 million barrels per day as of 2023, used for transportation, plastics, heating, and industrial processes.',
      'US alone: ~20M barrels/day. China: ~15M. EU: ~10M. Rest of world: ~55M. Total: ~100M barrels/day.',
      'The US alone consumes about 20 million barrels per day. Scale up to the rest of the world.',
      NULL,
      'EIA / IEA',
      '2023',
      95000000,
      105000000,
      ARRAY['oil', 'energy', 'consumption', 'infrastructure']::text[],
      'active'
    ),
(
      'How many nuclear power reactors are operating worldwide?',
      440,
      'reactor',
      'reactors',
      'infrastructure',
      'medium',
      'There are approximately 440 operable nuclear power reactors in 32 countries as of 2023, with another 57 under construction.',
      'US has ~93. France: ~56. China: ~55 (growing rapidly). Russia: ~37. Others: ~200. Total ~440.',
      'France gets ~70% of its electricity from nuclear. The US has the most reactors of any single country.',
      NULL,
      'World Nuclear Association',
      '2023',
      420,
      460,
      ARRAY['nuclear', 'energy', 'power', 'infrastructure']::text[],
      'active'
    ),
(
      'How many copies has Minecraft sold across all platforms?',
      238000000,
      'copy',
      'copies',
      'gaming',
      'medium',
      'Minecraft has sold over 238 million copies as of 2021, making it the best-selling video game of all time. It is available on PC, console, mobile, and other platforms.',
      'Minecraft is available on essentially every platform. It has been sold since 2011. At peak it was selling millions per month. Total across 10+ years: 200M+ is well-documented.',
      'Minecraft is the best-selling video game in history. It''s been available for over 10 years across every platform.',
      NULL,
      'Microsoft / Mojang',
      '2021',
      230000000,
      250000000,
      ARRAY['Minecraft', 'gaming', 'sales', 'video games']::text[],
      'active'
    ),
(
      'How many active players does Fortnite have per month?',
      230000000,
      'player',
      'players',
      'gaming',
      'medium',
      'Fortnite has approximately 230 million registered players, though monthly active users fluctuate significantly with new seasons and events. Epic Games reported 350M registered accounts in 2020.',
      'Fortnite launched 2017. By 2020: 350M registered accounts. Monthly active: subset of registered. Peak concurrent: 12.3M in 2020.',
      'Fortnite is free to play and has been extremely popular since 2018.',
      NULL,
      'Epic Games',
      '2020',
      200000000,
      350000000,
      ARRAY['Fortnite', 'gaming', 'players', 'Epic Games']::text[],
      'active'
    ),
(
      'How many Steam accounts are registered on the platform?',
      132000000,
      'account',
      'accounts',
      'gaming',
      'medium',
      'Steam has approximately 132 million active monthly users as of 2023. Total registered accounts are higher, but many are inactive.',
      'Steam is the dominant PC gaming platform. Valve reports ~132M monthly active users. Total registered accounts are higher (many are bots or inactive).',
      'Steam is the largest PC gaming platform. Think about how many PC gamers use Windows.',
      NULL,
      'Valve Steam statistics',
      '2023',
      120000000,
      150000000,
      ARRAY['Steam', 'gaming', 'Valve', 'PC gaming']::text[],
      'active'
    ),
(
      'How many hours have been spent by all players in total playing World of Warcraft since launch?',
      93000000000,
      'hour',
      'hours',
      'gaming',
      'unhinged',
      'WoW launched in 2004 and has had millions of players. A rough estimate: peak ~12M subscribers × average ~20 hrs/week × 52 weeks = 12.5B hrs/year. Over 20 years with varying player counts: ~50–100B hours total.',
      'Peak: 12M players. Average: 5M players over 20 years. 5M × 20 hr/week × 52 weeks × 20 years = 104 billion hours.',
      'WoW has had millions of dedicated players for 20 years. Some players spend dozens of hours per week.',
      NULL,
      'Industry estimates',
      '2004–2023',
      50000000000,
      150000000000,
      ARRAY['World of Warcraft', 'gaming', 'MMORPG', 'hours']::text[],
      'active'
    ),
(
      'How many games are available on the Steam platform?',
      70000,
      'game',
      'games',
      'gaming',
      'medium',
      'Steam has over 70,000 games available on the platform as of 2023. The store adds thousands of new games every year.',
      'Steam had ~1,000 games in 2008, grew rapidly after opening to indie developers. ~10,000+ games added per year in recent years. Total: ~70,000+ by 2023.',
      'Steam has been growing rapidly, adding thousands of indie games every year.',
      NULL,
      'Steam Spy / SteamDB',
      '2023',
      60000,
      80000,
      ARRAY['Steam', 'gaming', 'library', 'PC gaming']::text[],
      'active'
    ),
(
      'What is the population of Tokyo (greater metropolitan area)?',
      37400000,
      'person',
      'people',
      'cities',
      'easy',
      'Tokyo''s greater metropolitan area has approximately 37.4 million people, making it the most populous urban agglomeration in the world.',
      'Japan''s population: ~125M. Tokyo metro is the dominant city. If ~30% of Japan lives in the Tokyo area: 125M × 0.30 = 37.5M.',
      'Tokyo is the world''s largest metropolitan area. Japan has about 125 million people total.',
      NULL,
      'UN World Urbanization Prospects',
      '2023',
      36000000,
      38500000,
      ARRAY['Tokyo', 'Japan', 'population', 'cities']::text[],
      'active'
    ),
(
      'How many subway stations does the New York City subway system have?',
      472,
      'station',
      'stations',
      'cities',
      'medium',
      'The New York City Subway has 472 stations, making it the subway system with the most stations in the world.',
      'NYC subway has 27 lines. If average ~17 stations per line: 27 × 17 ≈ 460. Some stations are served by multiple lines. Total unique: 472.',
      'The NYC subway is one of the world''s largest. It has over 25 lines.',
      NULL,
      'MTA New York City Transit',
      'Reference',
      465,
      480,
      ARRAY['NYC', 'subway', 'transit', 'cities']::text[],
      'active'
    ),
(
      'How many skyscrapers (buildings over 150m tall) are in Shanghai?',
      163,
      'skyscraper',
      'skyscrapers',
      'cities',
      'hard',
      'Shanghai has approximately 163 buildings over 150 meters tall as of 2023, making it one of the cities with the most skyscrapers globally. The Shanghai Tower at 632m is the tallest.',
      'Major Chinese cities have been building rapidly since 1990s. Shanghai''s Pudong district alone has dozens. Total city-wide skyscrapers: 100–200 over 150m.',
      'Shanghai is one of the fastest-growing skyscraper cities. The Pudong district is particularly dense.',
      NULL,
      'CTBUH Skyscraper Center',
      '2023',
      140,
      200,
      ARRAY['Shanghai', 'skyscrapers', 'cities', 'architecture']::text[],
      'active'
    ),
(
      'How many people live in Los Angeles county?',
      9900000,
      'person',
      'people',
      'cities',
      'easy',
      'Los Angeles County has approximately 9.9 million residents, making it the most populous county in the United States.',
      'California population: ~39M. LA is the dominant county. Perhaps 25% of California lives in LA county: 39M × 0.25 = 9.75M.',
      'California has 39 million people. LA County is its most populous county.',
      NULL,
      'US Census Bureau',
      '2023',
      9500000,
      10200000,
      ARRAY['Los Angeles', 'California', 'population', 'cities']::text[],
      'active'
    ),
(
      'How many bicycles are in Amsterdam?',
      900000,
      'bicycle',
      'bicycles',
      'cities',
      'medium',
      'Amsterdam has approximately 900,000 bicycles — more bikes than people (population ~920,000). Cycling is the primary mode of transport in the city.',
      'Amsterdam population: ~920,000. It''s world-famous for cycling. If each person averages close to 1 bike and many households have multiple: ~900,000 bikes.',
      'Amsterdam is famously bike-friendly. They have more bicycles than people.',
      NULL,
      'Amsterdam municipality',
      'Reference',
      800000,
      1000000,
      ARRAY['Amsterdam', 'bicycles', 'Netherlands', 'cities']::text[],
      'active'
    );