import * as fs from 'fs';
import * as path from 'path';

function escapeSql(str: string | undefined | null): string {
  if (str === undefined || str === null) return 'NULL';
  return "'" + (str as string).replace(/'/g, "''") + "'";
}


const dataDir = './src/data';
const files = fs.readdirSync(dataDir).filter(f => f.startsWith('batch_') && f.endsWith('.json'));

let allQuestions: any[] = [];

for (const file of files) {
  try {
    const content = fs.readFileSync(path.join(dataDir, file), 'utf8');
    const questions: any[] = JSON.parse(content);
    allQuestions = allQuestions.concat(questions);
    console.log(`Loaded ${questions.length} from ${file}`);
  } catch (e: any) {
    console.error(`Failed to load ${file}:`, e?.message);
  }
}

console.log(`Total new questions generated by Swarm: ${allQuestions.length}`);

const values = allQuestions.map((q: any) => `(
  ${escapeSql(q.text)},
  ${escapeSql(q.referenceAnswer)},
  ${escapeSql(q.unit)},
  ${escapeSql(q.unitPlural)},
  ${escapeSql(q.category)},
  ${escapeSql(q.difficulty)},
  ${escapeSql(q.explanation)},
  ${escapeSql(q.estimationApproach)},
  ${escapeSql(q.hint)},
  ${escapeSql(q.source)},
  ${escapeSql(q.sourceName)},
  ${escapeSql(q.referencePeriod)},
  ${q.uncertaintyLow ?? 'NULL'},
  ${q.uncertaintyHigh ?? 'NULL'},
  ARRAY[${Array.isArray(q.tags) ? q.tags.map((t: string) => escapeSql(t)).join(', ') : ''}]::text[],
  'active'
)`);

const sql = `INSERT INTO questions (text, reference_answer, unit, unit_plural, category, difficulty, explanation, estimation_approach, hint, source, source_name, reference_period, uncertainty_low, uncertainty_high, tags, status) VALUES \n${values.join(',\n')};\n`;

fs.writeFileSync('./supabase/seed_swarm.sql', sql);
console.log('Successfully generated seed_swarm.sql!');

